# docker-compose.yml
version: '2'

services:
    mps-arch:
        image: mps-arch
        build:
          context: .
          dockerfile: Dockerfile.arch
        networks:
          - mps
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    mps-debian:
        image: mps-debian
        build:
          context: .
          dockerfile: Dockerfile.debian
        networks:
          - mps
        stdin_open: true # docker run -i
        tty: true        # docker run -t
networks:
  mps:
