FROM debian
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update --yes && apt upgrade --yes
RUN apt install git make sudo htop bash xterm --yes 
ENV TERM=xterm 
RUN mkdir /mps 
RUN git clone https://github.com/livemps/mps-base.git /mps
RUN cd /mps && make min DISTRO=debian
CMD ["/bin/bash", "-i", "/bin/bash"]
ENTRYPOINT ["/bin/sh", "-c"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
