FROM archlinux
RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "Yes" | pacman --noconfirm -Syy && echo "Yes" | pacman --noconfirm -Syu
RUN echo "Yes" | pacman --noconfirm -S git make sudo htop  
ENV TERM=xterm
RUN mkdir /mps 
RUN git clone https://github.com/livemps/mps-base.git /mps \
        && cd /mps && make aur DISTRO=arch

CMD ["/bin/bash", "-i", "/bin/bash"]
ENTRYPOINT ["/bin/sh", "-c"]
