FROM debian
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update --yes && apt upgrade --yes
RUN apt install git make sudo htop bash --yes #\
#    && mkdir /mps-base
#COPY . /mps-base
RUN git clone https://github.com/livemps/mps-base.git \
#RUN cd /mps-base && make standard DISTRO=debian
#ENTRYPOINT ["/bin/sh", "-c", "htop"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["/bin/bash"]

